### ISSUE TITLE
Transformer and axion_induced_modes

### ISSUE THREAD

**Issue by J-co** [mppmu/BoostFractor.jl#17]
Hi,

it seems that transformer() calls axion_induced_modes in its arguments without specifying the frequency. 
`emit=axion_induced_modes(coords,modes;B=nothing,velocity_x=velocity_x,diskR=diskR)`

Therefore axion_induced_modes uses its default of 20 GHz regardless of the frequency passed to transformer.
Seems serious, but I haven't tested its impact. It can only affect the result when including velocities...

Jacob

**Comment by jhbdiehl** [comment]
Stefans velocity studies were done at 22GHz and the endresult was that it doesn't really matter. I think this result should be unaffected. Nevertheless, I'll definitely fix it asap. thanks a bunch!

**Comment by knirck** [comment]
Yes, I remember this bug, I found it as well when I compared the transformer and dancer results with velocity and found a magic 10% discrepancy in the velocity I had to choose to make it match. (The effective velocity simulated should be just v_eff = v_input 20 GHz / f).  I thought I had fixed it, but apparently I forgot it and just scaled the velocity...
Thanks, Johannes, if you fix it!

**Comment by knirck** [comment]
I see it is fixed, so closing the issue. Thanks!
